# Generated by Django 2.0.3 on 2018-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('custom_key', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=100)),
            ],
        ),
    ]
